--CREATE TABLE fillOrders (
--	id int NOT NULL AUTO_INCREMENT,
--	productId int NOT NULL,
--	createDate DATETIME NOT NULL,
--	processDate DATETIME,
--	processed BOOLEAN NOT NULL,
--	stock int NOT NULL,
--	PRIMARY KEY (id)
--)